### ISSUE TITLE
Use json output from gfold

### ISSUE THREAD

**Issue by AckslD** [AckslD/nvim-gfold.lua#1]
Currently we parse the output of gfold using some simple lua code. But when `gfold` [supports](https://github.com/nickgerace/gfold/issues/176) output as `json` we should just use this.

**Comment by nickgerace** [comment]
The first RC containing this feature contained a few bugs blocking manual testing, but the second RC should be ready for early testing to help here.

Release: https://github.com/nickgerace/gfold/releases/tag/4.0.0-rc.2
Diff: https://github.com/nickgerace/gfold/compare/4.0.0-rc.1...4.0.0-rc.2
Cargo install option: `cargo install --locked --version 4.0.0-rc.2 gfold`

**Comment by nickgerace** [comment]
gfold 4 has been released. JSON output can be selected via the new display option.

```shell
gfold -d json
```

In `gfold.toml`, you can set the option to run in this display mode by default:

```toml
# Generated by executing: gfold -d json --dry-run
display_mode = 'Json'
```

If there's a bug or issue, I've architected the v4 codebase to be a little easier to fix domain-specific issues, so I'm hoping a patch or minor release would be all that's necessary for a fix to unblock this issue. However, I'm hoping `4.0.0` will work!
